services:
  cli:
    build: "."
    hostname: sv-kubernetes
    network_mode: host
    image: sv-kubernetes:local
    init: true
    environment:
      SV_KUBERNETES_PATH: ${SV_KUBERNETES_PATH}
      IS_DOCKER_DESKTOP: ${IS_DOCKER_DESKTOP}
    volumes:
      - "./:/sv"
      - "~/.kube:/root/.kube"
      - "~/.ssh:/root/.ssh"
      - "./internal/gcloud:/root/.config/gcloud"
      - "//var/run/docker.sock:/var/run/docker.sock"
