services:
  cli:
    build: "."
    hostname: sv-kubernetes
    network_mode: host
    image: sv-kubernetes:local
    init: true
    environment:
      SV_KUBERNETES_MOUNT_PATH: ${SV_KUBERNETES_MOUNT_PATH}
      IS_DOCKER_DESKTOP: ${IS_DOCKER_DESKTOP}
    volumes:
      - "./:/sv"
      - "~/.kube:/root/.kube"
      - "~/.ssh:/root/.ssh"
      - "./internal/gcloud:/root/.config/gcloud"
      - "//var/run/docker.sock:/var/run/docker.sock"

  deploy-gce:
    image: ${IMAGE_REGISTRY:-}sv-deploy-gce:${IMAGE_TAG:-local}
    build:
      context: .
      dockerfile: ./deploy/gce/Dockerfile
      cache_from:
        - ${IMAGE_REGISTRY:-}sv-deploy-gce:${IMAGE_TAG:-local}
    init: true
    environment:
      PROJECT_ID: sv-shared-231700
      REPO_NAME: sv-kubernetes-example
      BRANCH_NAME: develop
      ZONE: us-east1-b
      GCLOUD_SERVICE_KEY: ${SERVICE_KEY:-}
    volumes:
      - "./:/sv"
      - "~/.kube:/root/.kube"
      - "~/.ssh:/root/.ssh"
      - "./internal/gcloud:/root/.config/gcloud"
      - "//var/run/docker.sock:/var/run/docker.sock"
