version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
    machine:
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              echo 'export TAG="latest"' >> $BASH_ENV
            else
              echo 'export TAG="dev"' >> $BASH_ENV
            fi
      - run:
          name: Build Container
          command: |
            docker login -u _json_key -p "${GCLOUD_SERVICE_KEY}" https://gcr.io
            docker pull gcr.io/${SV_SHARED_NAME}/sv-deploy-gce:${TAG} || true
            docker build -t gcr.io/${SV_SHARED_NAME}/sv-deploy-gce:${TAG} \
              --cache-from gcr.io/${SV_SHARED_NAME}/sv-deploy-gce:${TAG} \
              --build-arg SV_KUBERNETES_BRANCH=${SV_KUBERNETES_BRANCH:-master} .
            docker push gcr.io/${SV_SHARED_NAME}/sv-deploy-gce:${TAG}