---
version: 2.1

orbs:
  circleci-config: simpleviewinc/circleci-config@2

common_config: &common_config
  context: default
  filters:
    branches:
      only:
        - develop
        - master
        - /pull.*/

workflows:
  build:
    jobs:
      - circleci-config/gcr_build_push_compose:
          <<: *common_config
          job_docker_compose_build_services: cli,deploy
          job_docker_source_image: sv-kubernetes-deploy
          job_docker_target_image: sv-deploy-gce
      - circleci-config/complete:
          <<: *common_config
          requires:
            - circleci-config/gcr_build_push_compose
